  
name: Crates-Index_Proxy Docker image build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    uses: open-rust-initiative/freighter/.github/workflows/do-common-build.yml@main
    with:
      image-name: crates-index-proxy:latest
    secrets:
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
